config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "home#index"
  resources :campaigns do 
    resources :delivery_report, :only => [:index]
  end

  resources :responses

  get 'followers' => 'home#followers', :as => :followers
  get 'follower/profile/:id' => 'home#profile', :as => :profile
  get 'status' => 'home#status', :as => :status

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  has_many :delivery_reports  
  belongs_to :message
  belongs_to :user

  def campaigns
    Campaign.where(user_id: self.id).order("created_at DESC")
  end

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/delayed_job.rb
class DelayedJob < ActiveRecord::Base 
end

app/models/delivery_report.rb
class DeliveryReport < ActiveRecord::Base
  belongs_to :campaign
end

app/models/image.rb
class Image < ActiveRecord::Base

  has_one :message, as: :messageable  
  mount_uploader :name, ImageUploader

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :messageable, polymorphic: true
  has_one :campaign
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
end

app/models/text.rb
class Text < ActiveRecord::Base
  has_one :message, as: :messageable
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  mount_uploader :name, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login
  has_many :campaigns
  has_many :responses

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    } # etc.

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def followers
    followers = REDIS.smembers("wonderer007:followers")
  end

  def unread_messages
    self.responses.where(read:false).count
  end

  def messages_count
    self.responses.count
  end

  def campaigns_count
    self.campaigns.count
  end

  def pending_campaigns
    self.campaigns.where(status: false).count
  end

  def followers_count
    REDIS.smembers("#{self.username}:followers").count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.html
      format.json { render json: CampaignsDatatable.new(view_context) }
    end
  end

  def new
    @campaign = Campaign.new
  end

  def create

    if params[:campaign][:type].to_i == 1
      text = Text.create(msg: params[:campaign][:text])
      id  = text.id
      type = text.class.name
    else
      image = Image.create(name: params[:campaign][:avatar])
      id  = image.id
      type = image.class.name
    end

    message   = Message.create(messageable_id: id, messageable_type: type)
    campaign  = Campaign.new campaign_params
    campaign.user_id = current_user.id
    campaign.message = message

    campaign.save

    Delayed::Job.enqueue(CampaignJob.new(campaign.id))
    flash[:sucess] = "Campaign created sucessfully"
    redirect_to campaigns_path

  end

  def show
    @campaign = current_user.campaigns.find params[:id]
  end

  private

    def campaign_params
      params.require(:campaign).permit(:name)
    end

end

app/controllers/delivery_report_controller.rb
class DeliveryReportController < ApplicationController

  before_action :authenticate_user!
  before_action :set_campaign

  def index

    respond_to do |format|
      format.html
      format.json { render json: DeliveryReportsDatatable.new(view_context, @campaign) }
    end

  end

  private

    def set_campaign
      @campaign = Campaign.find params[:campaign_id]
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!
  
  def index
  end

  def followers
    @followers = current_user.followers
  end

  def profile
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_response, :only => [:show]

  def index
    respond_to do |format|
      format.html
      format.json { render json: ResponsesDatatable.new(view_context, current_user) }
    end
  end

  def show
    @responses = Response.order(id: :desc).where(:phone_number => @response.phone_number).limit(10)
  end

  private

    def set_response
      @response = Response.find params[:id]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/helpers/delivery_report_helper.rb
module DeliveryReportHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/campaigns/index.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Campaigns
      </h1>
    </section>
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title pull-right">
                <a href=<%= new_campaign_path %> class="btn btn-block btn-primary">New Campaign</a>
              </h3>
            </div>
            <div class="box-body">
              <table id="campaigns" class="table table-bordered table-hover" data-source="<%= campaigns_path(format: "json") %>">
                <thead>
                  <tr>
                    <th>Campaign ID</th>
                    <th>Campaign Name</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

<script>
  $(function () {
    var table = $('#campaigns').DataTable({
      "order": [[ 0, "desc" ]],
      "columnDefs": [{
          "targets": [4,5],
          "orderable": false
      }],
      "sAjaxSource": $('#campaigns').data('source'),
      "bProcessing": false,
      "bServerSide": true,
      "bDeferRender": true,
      "language": {
          "lengthMenu": "Display _MENU_ campaigns per page",
          "zeroRecords": "No campaign found - sorry",
          "info": "Showing page _PAGE_ of _PAGES_",
          "infoEmpty": "No campaigns available",
          "infoFiltered": "(filtered from _MAX_ total campaigns)"
      },
      "destroy": true
    });
  });
</script>

app/views/campaigns/new.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        New Campaign
      </h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box" style="padding:20px;">
            <div class="box-header">
            </div>
            <br/>
            <div class="box-body table-responsive no-padding">
              <div class="col-md-6 col-xs-offset-3">

                <%= form_tag(campaigns_path, :method=>'post', :multipart => true) do %>

                  <form role="form">
                    <div class="box-body">
                      <div class="form-group">
                        <%= text_field_tag "campaign[name]", "", class: 'form-control', placeholder: "Campaign Name", required:true %>
                      </div>
                    </div>

                    <div class="box-body">
                      <div class="form-group">

                       <%= select_tag("campaign[type]", 
                            options_for_select([['Text ', '1'],
                                     ['Image ', '2']]) {} , {prompt: "Select Campaign Type", :class => 'form-control', required:true }) %>

                      </div>
                    </div>

                    <div class="box-body" id="text">
                      <div class="form-group">

                       <%= text_area_tag 'campaign[text]', nil, class: 'form-control',placeholder: "Campaign Text"  %>
                      </div>
                    </div>


                    <div class="box-body" id="image">
                      <div class="form-group">
                        <label for="file">Upload Image</label> <%= file_field_tag "campaign[avatar]", accept: "image/*" %>
                      </div>
                    </div>

                    <button type="submit" class="btn btn-primary pull-right">Create Campaign</button>

                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

<script>
  $(document).ready(function() {

    $('#example').DataTable({});
    $("#text").css("display", "none");
    $("#image").css("display", "none");

    $( "#campaign_type" ).change(function() {

      if($("#campaign_type").val() == 1) {
        $("#text").css("display", "block");
        $("#image").css("display", "none");

        $("#campaign_text").prop("required", "true");
        $("#campaign_avatar").removeProp("required", "false");

      }
      else if ($("#campaign_type").val() == 2) {
        $("#image").css("display", "block");
        $("#text").css("display", "none");

        $("#campaign_text").removeProp("required", "false");
        $("#campaign_avatar").prop("required", "true");
      }
      else {

        $("#text").css("display", "none");
        $("#image").css("display", "none");

        $("#campaign_text").removeProp("required", "false");
        $("#campaign_avatar").removeProp("required", "false");
      }

    });

  });
</script>

app/views/campaigns/show.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Campaign Detail
      </h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title"><%= @campaign.name %></h3>
                </div>
                <div class="box-body">
                  <table class="table table-bordered">
                    <tbody>
                      <tr>
                        <th>Campaign ID</th>
                        <td><%= @campaign.id %></td>
                      </tr>

                      <tr>
                        <th>Campaign Type</th>
                        <td><%= @campaign.message.messageable.class.name %></td>
                      </tr>

                      <% if @campaign.message.messageable.class.name == "Text" %>
                        <tr>
                          <th>Campaign Text</th>
                          <td><%= @campaign.message.messageable.msg %></td>
                        </tr>
                      <% else %>
                        <tr>
                          <th>Campaign Image</th>
                          <td>
                            <img src=<%= @campaign.message.messageable.name.url(:thumb) %> >
                          </td>
                        </tr>

                      <%end%>

                      <tr>
                        <th>Total Recipents</th>
                        <td><%= @campaign.delivery_reports.count %></td>
                      </tr>

                      <tr>
                        <th>Start Time</th>
                        <td><%= @campaign.created_at.to_s %></td>
                      </tr>

                      <tr>
                        <th>End Time</th>
                        <td>
                          <%=
                            if @campaign.end_time.nil?
                              "-"
                            else
                              @campaign.end_time.localtime.to_s 
                            end
                          %>
                        </td>
                      </tr>

                      <tr>
                        <th>Status</th>
                        <td >
                          <% if @campaign.status %>
                            <span class="label label-success">Completed</span>
                          <% else %>
                            <span class="label label-danger">Pending</span>
                          <% end %>
                        </td>
                      </tr>

                      <tr>
                        <th>Delivery Reports</th>
                        <td>
                          <a href=<%= campaign_delivery_report_index_path(@campaign)%> >
                            Delivery Reports
                          </a>
                        </td>
                      </tr>
                  </tbody></table>
                </div>
              </div>
            </div>
      </div>
    </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

app/views/delivery_report/index.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Delivery Reports
      </h1>
    </section>
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box" style="padding:20px;">
            <div class="box-header">
              <h3 class="box-title">
              </h3>
              <div class="box-tools">
              </div>
            </div>
            <br/>
            <div class="box-body table-responsive no-padding">
              <table id="example" class="table table-bordered table-hover" data-source="<%= campaign_delivery_report_index_path(@campaign,format: "json") %>">
                <thead>
                  <tr>
                    <th>Phone #</th>
                    <th>Delivery Time</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

<script>
  $(function () {
    var table = $('#example').DataTable({
      "order": [[ 1, "desc" ]],
      "columnDefs": [{
          "targets": [2],
          "orderable": false
      }],
      "sAjaxSource": $('#example').data('source'),
      "bProcessing": false,
      "bServerSide": true,
      "bDeferRender": true,
      "bDeferRender": true,
      "language": {
          "lengthMenu": "Display _MENU_ reports per page",
          "zeroRecords": "No report found - sorry",
          "info": "Showing page _PAGE_ of _PAGES_",
          "infoEmpty": "No reports available",
          "infoFiltered": "(filtered from _MAX_ total reports)"
      }

    });
  });
</script>

app/views/home/followers.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Followers
      </h1>
    </section>
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"></h3>
            </div>
            <div class="box-body">
              <table id="followers" class="table table-bordered table-hover" cellspacing="0" width="100%">
                  <thead>
                      <tr>
                          <th>Phone #</th>
                          <th>Actions</th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @followers.each do |follower|%>
                      <tr>
                        <td><a href=<%= profile_path(follower) %> ><%= follower%></a></td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a></td>
                      </tr>
                    <%end%>
                  </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>    
    </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

<script>
  $(document).ready(function() {

    var table = $('#followers').DataTable({
      "columnDefs": [{
          "targets": [1],
          "orderable": false
      }],
      "bDeferRender": true,
      "language": {
          "lengthMenu": "Display _MENU_ followers per page",
          "zeroRecords": "No follower found - sorry",
          "info": "Showing page _PAGE_ of _PAGES_",
          "infoEmpty": "No followers available",
          "infoFiltered": "(filtered from _MAX_ total followers)"
      }

    });
  });



</script>

app/views/home/index.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3><%= current_user.followers_count %></h3>
              <p>Followers</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href=<%= followers_path %> class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3><%= current_user.messages_count %></h3>
              <p>Replys</p>
            </div>
            <div class="icon">
              <i class="ion ion-reply"></i>
            </div>
            <a href=<%= responses_path %> class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3><%= current_user.campaigns_count %></h3>
              <p>Campaigns</p>
            </div>
            <div class="icon">
              <i class="ion ion-chatbubble"></i>
            </div>
            <a href=<%= campaigns_path %> class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>65</h3>
              <p>Page Visitors</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->
      </div><!-- /.row -->

    </section><!-- /.content -->
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

app/views/home/puffit.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Puffit IM
        <small>Followers</small>
      </h1>
      <br/>
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Followers List</h3>
            </div>
            <div class="box-body">
              <table class="table table-bordered">
                <tbody><tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Phone #</th>
                  <th style="width: 40px">Actions</th>
                </tr>

                <% @followers["contacts"].each_with_index do |follower, index|%>
                  <tr>
                    <td><%= index %></td>
                    <td><%= follower["name"] %></td>
                    <td><%= follower["phone"] %></td>
                    <td>
                      <a href=""><i class="fa fa-envelope"></i></a>
                    </td>
                  </tr>
                <% end %>

              </tbody></table>
            </div><!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">»</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>    
  </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pufit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="hold-transition skin-blue sidebar-mini">
  <%= yield %>
</body>
</html>

app/views/responses/index.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Messages
      </h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box" style="padding:20px;">
            <div class="box-header">
              <h3 class="box-title"></h3>
              <div class="box-tools">
              </div>
            </div>
            <br/>
            <div class="box-body table-responsive no-padding">
              <table id="messages" class="table table-bordered table-hover" data-source="<%= responses_path(format: "json") %>">
                <thead>
                  <tr>
                    <th>Phone Number</th>
                    <th>Last Message</th>
                    <th>Recived Time</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>

<script>
  $(document).ready(function() {

    $(function () {
      var table = $('#messages').DataTable({
        "columnDefs": [{
            "targets": [3],
            "orderable": false
        }],
        "sAjaxSource": $('#messages').data('source'),
        "bProcessing": false,
        "bServerSide": true,
        "bDeferRender": true,
        "language": {
            "lengthMenu": "Display _MENU_ replies per page",
            "zeroRecords": "No reply found - sorry",
            "info": "Showing page _PAGE_ of _PAGES_",
            "infoEmpty": "No replies available",
            "infoFiltered": "(filtered from _MAX_ total replies)"
        }
      });
    });

  });
</script>

app/views/responses/show.html.erb
<div class="wrapper">
  <%= render 'shared/header.html.erb' %>
  <%= render 'shared/main_navigation.html.erb' %>
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Message Details
      </h1>
    </section>

    <section class="content">
      <div class="row">
      <div class="col-md-12">
        <div class="box box-primary direct-chat direct-chat-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">From <%= @response.phone_number %></h3>
                </div>
                <div class="box-body">

                  <div class="direct-chat-messages">
                    <% @responses.each do |response|%>
                      <div class="direct-chat-msg">
                        <div class="direct-chat-info clearfix">
                          <span class="direct-chat-timestamp pull-right">
                            <%= response.created_at.localtime.to_s %>
                          </span>
                        </div>
                        <div class="direct-chat-text">
                          <%= response.message %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
                <div class="box-footer">
                  <form action="#" method="post">
                    <div class="input-group">
                      <input type="text" name="message" placeholder="Type Reply ..." class="form-control">
                      <span class="input-group-btn">
                        <button type="button" id="reply" class="btn btn-primary btn-flat">Send</button>
                      </span>
                    </div>
                  </form>
                </div>
        </div>
      </div>
      </div>
    </section>
  </div>
  <%= render 'shared/footer.html.erb' %>
</div>
<script>
  $(function() {
    $(document).on('click', '#reply', function() { 
      swal({
  title: "Please Wait !!!",   text: "",   timer: 2000,   showConfirmButton: false        });
     });
  });
</script>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.0.0
  </div>
  <strong>Copyright &copy; 2015-2016 <a href="<%root_path %>">PUFFIT IM</a>.</strong> All rights reserved.
</footer>

app/views/shared/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%= root_path %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">puffit</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>PUFFIT</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
        <%= link_to(destroy_user_session_path, :class => "ion ion-log-out", method: :delete) do %>
          <span class="hidden-xs">Sign Out</span>
        <% end %>
        </li>
        <!-- Control Sidebar Toggle Button -->
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_main_navigation.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="<%= root_path %>">
          <i class="fa fa-tachometer"></i> <span>Dashboad</span>
        </a>
      </li>
      <li>
        <a href="<%= responses_path %>">
          <i class="fa fa-envelope"></i> <span>Inbox</span>
        </a>
      </li>
      <li>
        <a href="<%= followers_path %>">
          <i class="fa fa-user"></i> <span>Followers</span>
        </a>
      </li>

      <li>
        <a href="<%= campaigns_path  %>">
          <i class="fa fa-wechat"></i> <span>Campaigns</span>
          <% if current_user.pending_campaigns > 0 %>
            <small class="label pull-right bg-red">
              <%= current_user.pending_campaigns %>
            </small>
          <% end %>

        </a></li>
    </ul>
  </section>
</aside>